defaults: &defaults
  additional_info: true
  contact_phone: true
  organizer: true
  description: true
  benefit: true
  placement: true
  address: true
  time: true
  electricity: false
  light: false
  fire: false
  noise: false
  nature: false
  moop: false
  plan: true
  cocreation: true
  neighbors: true
  marketing: true
  responsibility_check: true
  budgetplan: false
  seeking_members: false
  granting: false
  user_authentication_codes: false
  add_to_list: false
  granting_active: false
  footer_text: false
  footer_logo: false
  creation_sidebar_welcome: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
